# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created: Thu Apr 29 22:35:47 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_configureWindow(object):
    def setupUi(self, configureWindow):
        configureWindow.setObjectName("configureWindow")
        configureWindow.setWindowModality(QtCore.Qt.WindowModal)
        configureWindow.resize(1024, 723)
        configureWindow.setMinimumSize(QtCore.QSize(200, 0))
        configureWindow.setModal(False)
        self.verticalLayoutWidget = QtGui.QWidget(configureWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 1021, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setIconSize(QtCore.QSize(80, 80))
        self.listWidget.setObjectName("listWidget")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Collection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon)
        self.horizontalLayout.addWidget(self.listWidget)
        self.stackedWidget = QtGui.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(700, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.p_Collection = QtGui.QWidget()
        self.p_Collection.setObjectName("p_Collection")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.p_Collection)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 701, 611))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 25, -1, 25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.b_AddT = QtGui.QPushButton(self.verticalLayoutWidget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_AddT.setIcon(icon1)
        self.b_AddT.setObjectName("b_AddT")
        self.horizontalLayout_2.addWidget(self.b_AddT)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.b_RemoveT = QtGui.QPushButton(self.verticalLayoutWidget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_RemoveT.setIcon(icon2)
        self.b_RemoveT.setObjectName("b_RemoveT")
        self.horizontalLayout_2.addWidget(self.b_RemoveT)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.songDirList = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.songDirList.setAlternatingRowColors(True)
        self.songDirList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.songDirList.setObjectName("songDirList")
        self.verticalLayout.addWidget(self.songDirList)
        self.stackedWidget.addWidget(self.p_Collection)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(configureWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(configureWindow)

    def retranslateUi(self, configureWindow):
        configureWindow.setWindowTitle(QtGui.QApplication.translate("configureWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("configureWindow", "Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtGui.QApplication.translate("configureWindow", "Choose Track Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.b_AddT.setText(QtGui.QApplication.translate("configureWindow", "Add..", None, QtGui.QApplication.UnicodeUTF8))
        self.b_RemoveT.setText(QtGui.QApplication.translate("configureWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
