# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created: Thu Apr 29 22:35:47 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 762)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.b_Prev = QtGui.QToolButton(self.centralWidget)
        self.b_Prev.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/player_prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_Prev.setIcon(icon1)
        self.b_Prev.setIconSize(QtCore.QSize(24, 24))
        self.b_Prev.setAutoRaise(True)
        self.b_Prev.setObjectName("b_Prev")
        self.horizontalLayout_3.addWidget(self.b_Prev)
        self.b_Play = QtGui.QToolButton(self.centralWidget)
        self.b_Play.setStyleSheet("None")
        self.b_Play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/player_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_Play.setIcon(icon2)
        self.b_Play.setIconSize(QtCore.QSize(24, 24))
        self.b_Play.setCheckable(True)
        self.b_Play.setAutoRaise(True)
        self.b_Play.setObjectName("b_Play")
        self.horizontalLayout_3.addWidget(self.b_Play)
        self.b_Stop = QtGui.QToolButton(self.centralWidget)
        self.b_Stop.setEnabled(True)
        self.b_Stop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/player_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_Stop.setIcon(icon3)
        self.b_Stop.setIconSize(QtCore.QSize(24, 24))
        self.b_Stop.setAutoRaise(True)
        self.b_Stop.setObjectName("b_Stop")
        self.horizontalLayout_3.addWidget(self.b_Stop)
        self.b_Next = QtGui.QToolButton(self.centralWidget)
        self.b_Next.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/player_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_Next.setIcon(icon4)
        self.b_Next.setIconSize(QtCore.QSize(24, 24))
        self.b_Next.setAutoRaise(True)
        self.b_Next.setObjectName("b_Next")
        self.horizontalLayout_3.addWidget(self.b_Next)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.progressBar = QtGui.QProgressBar(self.centralWidget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.centralWidget)
        self.volumeSlider.setMaximumSize(QtCore.QSize(200, 200))
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_3.addWidget(self.volumeSlider)
        self.volumeDisplay = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeDisplay.sizePolicy().hasHeightForWidth())
        self.volumeDisplay.setSizePolicy(sizePolicy)
        self.volumeDisplay.setMinimumSize(QtCore.QSize(24, 0))
        self.volumeDisplay.setObjectName("volumeDisplay")
        self.horizontalLayout_3.addWidget(self.volumeDisplay)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.parentTabs = QtGui.QTabWidget(self.splitter)
        self.parentTabs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parentTabs.sizePolicy().hasHeightForWidth())
        self.parentTabs.setSizePolicy(sizePolicy)
        self.parentTabs.setMinimumSize(QtCore.QSize(280, 0))
        self.parentTabs.setMaximumSize(QtCore.QSize(400, 16777215))
        self.parentTabs.setTabPosition(QtGui.QTabWidget.West)
        self.parentTabs.setDocumentMode(True)
        self.parentTabs.setObjectName("parentTabs")
        self.contentTab = QtGui.QWidget()
        self.contentTab.setObjectName("contentTab")
        self.gridLayout_2 = QtGui.QGridLayout(self.contentTab)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.contentTabs = QtGui.QTabWidget(self.contentTab)
        self.contentTabs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentTabs.sizePolicy().hasHeightForWidth())
        self.contentTabs.setSizePolicy(sizePolicy)
        self.contentTabs.setMinimumSize(QtCore.QSize(200, 0))
        self.contentTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.contentTabs.setUsesScrollButtons(False)
        self.contentTabs.setDocumentMode(True)
        self.contentTabs.setTabsClosable(False)
        self.contentTabs.setMovable(False)
        self.contentTabs.setObjectName("contentTabs")
        self.musicTab = QtGui.QWidget()
        self.musicTab.setObjectName("musicTab")
        self.gridLayout_12 = QtGui.QGridLayout(self.musicTab)
        self.gridLayout_12.setMargin(2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.trackTitle = QtGui.QLabel(self.musicTab)
        self.trackTitle.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(12)
        self.trackTitle.setFont(font)
        self.trackTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.trackTitle.setObjectName("trackTitle")
        self.gridLayout_12.addWidget(self.trackTitle, 4, 0, 1, 1)
        self.artistName = QtGui.QLabel(self.musicTab)
        self.artistName.setAlignment(QtCore.Qt.AlignCenter)
        self.artistName.setObjectName("artistName")
        self.gridLayout_12.addWidget(self.artistName, 5, 0, 1, 1)
        self.albumArt = QtGui.QLabel(self.musicTab)
        self.albumArt.setMinimumSize(QtCore.QSize(300, 300))
        self.albumArt.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.albumArt.setFont(font)
        self.albumArt.setFrameShape(QtGui.QFrame.StyledPanel)
        self.albumArt.setFrameShadow(QtGui.QFrame.Raised)
        self.albumArt.setLineWidth(6)
        self.albumArt.setText("")
        self.albumArt.setPixmap(QtGui.QPixmap(":/Icons/music.png"))
        self.albumArt.setAlignment(QtCore.Qt.AlignCenter)
        self.albumArt.setObjectName("albumArt")
        self.gridLayout_12.addWidget(self.albumArt, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem5, 6, 0, 1, 1)
        self.contentTabs.addTab(self.musicTab, "")
        self.lyricsTab = QtGui.QWidget()
        self.lyricsTab.setObjectName("lyricsTab")
        self.gridLayout_5 = QtGui.QGridLayout(self.lyricsTab)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lyrcBrowser = QtGui.QTextBrowser(self.lyricsTab)
        self.lyrcBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.lyrcBrowser.setFrameShadow(QtGui.QFrame.Sunken)
        self.lyrcBrowser.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lyrcBrowser.setOpenLinks(False)
        self.lyrcBrowser.setObjectName("lyrcBrowser")
        self.gridLayout_5.addWidget(self.lyrcBrowser, 0, 0, 1, 1)
        self.contentTabs.addTab(self.lyricsTab, "")
        self.wikipediaTab = QtGui.QWidget()
        self.wikipediaTab.setObjectName("wikipediaTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.wikipediaTab)
        self.gridLayout_4.setMargin(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.wikiView = QtWebKit.QWebView(self.wikipediaTab)
        self.wikiView.setAutoFillBackground(True)
        self.wikiView.setStyleSheet("")
        self.wikiView.setUrl(QtCore.QUrl("about:blank"))
        self.wikiView.setZoomFactor(1.0)
        self.wikiView.setObjectName("wikiView")
        self.gridLayout_4.addWidget(self.wikiView, 0, 0, 1, 1)
        self.contentTabs.addTab(self.wikipediaTab, "")
        self.gridLayout_2.addWidget(self.contentTabs, 0, 1, 1, 1)
        self.parentTabs.addTab(self.contentTab, "")
        self.collectionTab = QtGui.QWidget()
        self.collectionTab.setObjectName("collectionTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.collectionTab)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearSearch = QtGui.QToolButton(self.collectionTab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/edit-clear-locationbar-ltr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearSearch.setIcon(icon5)
        self.clearSearch.setIconSize(QtCore.QSize(24, 24))
        self.clearSearch.setAutoRaise(True)
        self.clearSearch.setObjectName("clearSearch")
        self.horizontalLayout.addWidget(self.clearSearch)
        self.srchCollect = QtGui.QLineEdit(self.collectionTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.srchCollect.setFont(font)
        self.srchCollect.setObjectName("srchCollect")
        self.horizontalLayout.addWidget(self.srchCollect)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.collectTree = QtGui.QTreeWidget(self.collectionTab)
        self.collectTree.setDragEnabled(True)
        self.collectTree.setAlternatingRowColors(True)
        self.collectTree.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.collectTree.setIndentation(15)
        self.collectTree.setRootIsDecorated(True)
        self.collectTree.setAnimated(True)
        self.collectTree.setExpandsOnDoubleClick(False)
        self.collectTree.setObjectName("collectTree")
        self.verticalLayout_2.addWidget(self.collectTree)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.parentTabs.addTab(self.collectionTab, "")
        self.playlistsTab = QtGui.QWidget()
        self.playlistsTab.setObjectName("playlistsTab")
        self.gridLayout_6 = QtGui.QGridLayout(self.playlistsTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addPlylstBttn = QtGui.QToolButton(self.playlistsTab)
        self.addPlylstBttn.setMinimumSize(QtCore.QSize(46, 32))
        self.addPlylstBttn.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.addPlylstBttn.setObjectName("addPlylstBttn")
        self.horizontalLayout_5.addWidget(self.addPlylstBttn)
        self.line_2 = QtGui.QFrame(self.playlistsTab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.rnmPlylstBtnn = QtGui.QToolButton(self.playlistsTab)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/edit-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rnmPlylstBtnn.setIcon(icon6)
        self.rnmPlylstBtnn.setIconSize(QtCore.QSize(24, 24))
        self.rnmPlylstBtnn.setAutoRaise(True)
        self.rnmPlylstBtnn.setObjectName("rnmPlylstBtnn")
        self.horizontalLayout_5.addWidget(self.rnmPlylstBtnn)
        self.delPlylstBttn = QtGui.QToolButton(self.playlistsTab)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delPlylstBttn.setIcon(icon7)
        self.delPlylstBttn.setIconSize(QtCore.QSize(24, 24))
        self.delPlylstBttn.setAutoRaise(True)
        self.delPlylstBttn.setObjectName("delPlylstBttn")
        self.horizontalLayout_5.addWidget(self.delPlylstBttn)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.playlistCollection = QtGui.QTreeWidget(self.playlistsTab)
        self.playlistCollection.setObjectName("playlistCollection")
        self.verticalLayout_5.addWidget(self.playlistCollection)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.parentTabs.addTab(self.playlistsTab, "")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_Clear = QtGui.QToolButton(self.layoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/edit-clear-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_Clear.setIcon(icon8)
        self.b_Clear.setIconSize(QtCore.QSize(24, 24))
        self.b_Clear.setAutoRaise(True)
        self.b_Clear.setObjectName("b_Clear")
        self.horizontalLayout_4.addWidget(self.b_Clear)
        self.svplyBttn = QtGui.QToolButton(self.layoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.svplyBttn.setIcon(icon9)
        self.svplyBttn.setIconSize(QtCore.QSize(24, 24))
        self.svplyBttn.setAutoRaise(True)
        self.svplyBttn.setObjectName("svplyBttn")
        self.horizontalLayout_4.addWidget(self.svplyBttn)
        self.b_Shuffle = QtGui.QToolButton(self.layoutWidget)
        self.b_Shuffle.setEnabled(True)
        self.b_Shuffle.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/roll.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_Shuffle.setIcon(icon10)
        self.b_Shuffle.setIconSize(QtCore.QSize(24, 24))
        self.b_Shuffle.setCheckable(True)
        self.b_Shuffle.setAutoRaise(True)
        self.b_Shuffle.setObjectName("b_Shuffle")
        self.horizontalLayout_4.addWidget(self.b_Shuffle)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.clearSearchPl = QtGui.QToolButton(self.layoutWidget)
        self.clearSearchPl.setIcon(icon5)
        self.clearSearchPl.setIconSize(QtCore.QSize(24, 24))
        self.clearSearchPl.setAutoRaise(True)
        self.clearSearchPl.setObjectName("clearSearchPl")
        self.horizontalLayout_4.addWidget(self.clearSearchPl)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.srchPlist = QtGui.QLineEdit(self.layoutWidget)
        self.srchPlist.setMinimumSize(QtCore.QSize(200, 0))
        self.srchPlist.setObjectName("srchPlist")
        self.horizontalLayout_4.addWidget(self.srchPlist)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.playlistTree = QtGui.QTableWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlistTree.sizePolicy().hasHeightForWidth())
        self.playlistTree.setSizePolicy(sizePolicy)
        self.playlistTree.setMinimumSize(QtCore.QSize(499, 0))
        self.playlistTree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.playlistTree.setStyleSheet("QTableWidget QTableWidgetItem:hover {\n"
"\n"
"background-color:blue;\n"
"}")
        self.playlistTree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.playlistTree.setProperty("showDropIndicator", False)
        self.playlistTree.setDragEnabled(True)
        self.playlistTree.setDragDropOverwriteMode(False)
        self.playlistTree.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.playlistTree.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.playlistTree.setAlternatingRowColors(True)
        self.playlistTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.playlistTree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.playlistTree.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.playlistTree.setShowGrid(False)
        self.playlistTree.setGridStyle(QtCore.Qt.SolidLine)
        self.playlistTree.setWordWrap(False)
        self.playlistTree.setCornerButtonEnabled(True)
        self.playlistTree.setObjectName("playlistTree")
        self.playlistTree.setColumnCount(4)
        self.playlistTree.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.playlistTree.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.playlistTree.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.playlistTree.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.playlistTree.setHorizontalHeaderItem(3, item)
        self.playlistTree.horizontalHeader().setVisible(True)
        self.playlistTree.horizontalHeader().setCascadingSectionResizes(True)
        self.playlistTree.horizontalHeader().setDefaultSectionSize(200)
        self.playlistTree.horizontalHeader().setMinimumSectionSize(70)
        self.playlistTree.verticalHeader().setVisible(False)
        self.playlistTree.verticalHeader().setCascadingSectionResizes(False)
        self.playlistTree.verticalHeader().setDefaultSectionSize(28)
        self.playlistTree.verticalHeader().setMinimumSectionSize(26)
        self.verticalLayout_3.addWidget(self.playlistTree)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1215, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuActions = QtGui.QMenu(self.menuBar)
        self.menuActions.setObjectName("menuActions")
        self.menu_Settings = QtGui.QMenu(self.menuBar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionConfigure = QtGui.QAction(MainWindow)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionRescan_Collection = QtGui.QAction(MainWindow)
        self.actionRescan_Collection.setObjectName("actionRescan_Collection")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionMinimise_to_Tray = QtGui.QAction(MainWindow)
        self.actionMinimise_to_Tray.setCheckable(True)
        self.actionMinimise_to_Tray.setChecked(True)
        self.actionMinimise_to_Tray.setObjectName("actionMinimise_to_Tray")
        self.actionClear_Current = QtGui.QAction(MainWindow)
        self.actionClear_Current.setObjectName("actionClear_Current")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setIcon(icon8)
        self.actionClear.setObjectName("actionClear")
        self.actionSave_2 = QtGui.QAction(MainWindow)
        self.actionSave_2.setIcon(icon9)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionUpdate_Collection = QtGui.QAction(MainWindow)
        self.actionUpdate_Collection.setObjectName("actionUpdate_Collection")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionRptOff = QtGui.QAction(MainWindow)
        self.actionRptOff.setCheckable(True)
        self.actionRptOff.setChecked(True)
        self.actionRptOff.setObjectName("actionRptOff")
        self.actionRptTrack = QtGui.QAction(MainWindow)
        self.actionRptTrack.setCheckable(True)
        self.actionRptTrack.setObjectName("actionRptTrack")
        self.actionRptAlbum = QtGui.QAction(MainWindow)
        self.actionRptAlbum.setCheckable(True)
        self.actionRptAlbum.setObjectName("actionRptAlbum")
        self.actionRptPlaylist = QtGui.QAction(MainWindow)
        self.actionRptPlaylist.setCheckable(True)
        self.actionRptPlaylist.setObjectName("actionRptPlaylist")
        self.actionRndOff = QtGui.QAction(MainWindow)
        self.actionRndOff.setCheckable(True)
        self.actionRndOff.setChecked(True)
        self.actionRndOff.setObjectName("actionRndOff")
        self.actionRndTrack = QtGui.QAction(MainWindow)
        self.actionRndTrack.setCheckable(True)
        self.actionRndTrack.setObjectName("actionRndTrack")
        self.actionRndAlbum = QtGui.QAction(MainWindow)
        self.actionRndAlbum.setCheckable(True)
        self.actionRndAlbum.setObjectName("actionRndAlbum")
        self.actionFavor = QtGui.QAction(MainWindow)
        self.actionFavor.setObjectName("actionFavor")
        self.actionPlay_Audio_CD = QtGui.QAction(MainWindow)
        self.actionPlay_Audio_CD.setObjectName("actionPlay_Audio_CD")
        self.actionPrevious_Track = QtGui.QAction(MainWindow)
        self.actionPrevious_Track.setObjectName("actionPrevious_Track")
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setCheckable(True)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionNext_Track = QtGui.QAction(MainWindow)
        self.actionNext_Track.setObjectName("actionNext_Track")
        self.actionUpdate = QtGui.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionRescan = QtGui.QAction(MainWindow)
        self.actionRescan.setObjectName("actionRescan")
        self.menuActions.addAction(self.actionOpen)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionQuit)
        self.menuActions.addAction(self.actionMinimise_to_Tray)
        self.menuActions.addSeparator()
        self.menu_Settings.addAction(self.actionUpdate)
        self.menu_Settings.addAction(self.actionRescan)
        self.menu_Settings.addAction(self.actionConfigure)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuActions.menuAction())
        self.menuBar.addAction(self.menu_Settings.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())
        self.label.setBuddy(self.srchPlist)

        self.retranslateUi(MainWindow)
        self.parentTabs.setCurrentIndex(1)
        self.contentTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "RhythmBird", None, QtGui.QApplication.UnicodeUTF8))
        self.b_Prev.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous Track", None, QtGui.QApplication.UnicodeUTF8))
        self.b_Play.setToolTip(QtGui.QApplication.translate("MainWindow", "Play/Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.b_Stop.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.b_Next.setToolTip(QtGui.QApplication.translate("MainWindow", "Next Track", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeDisplay.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.trackTitle.setText(QtGui.QApplication.translate("MainWindow", "Track Title", None, QtGui.QApplication.UnicodeUTF8))
        self.artistName.setText(QtGui.QApplication.translate("MainWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.contentTabs.setTabText(self.contentTabs.indexOf(self.musicTab), QtGui.QApplication.translate("MainWindow", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.contentTabs.setTabText(self.contentTabs.indexOf(self.lyricsTab), QtGui.QApplication.translate("MainWindow", "Lyrics", None, QtGui.QApplication.UnicodeUTF8))
        self.contentTabs.setTabText(self.contentTabs.indexOf(self.wikipediaTab), QtGui.QApplication.translate("MainWindow", "Wikipedia", None, QtGui.QApplication.UnicodeUTF8))
        self.parentTabs.setTabText(self.parentTabs.indexOf(self.contentTab), QtGui.QApplication.translate("MainWindow", "Context", None, QtGui.QApplication.UnicodeUTF8))
        self.clearSearch.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear Search Field", None, QtGui.QApplication.UnicodeUTF8))
        self.clearSearch.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.srchCollect.setToolTip(QtGui.QApplication.translate("MainWindow", "Search Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.srchCollect.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.collectTree.setSortingEnabled(True)
        self.collectTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Artist/Album", None, QtGui.QApplication.UnicodeUTF8))
        self.parentTabs.setTabText(self.parentTabs.indexOf(self.collectionTab), QtGui.QApplication.translate("MainWindow", "Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.addPlylstBttn.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.rnmPlylstBtnn.setText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.delPlylstBttn.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistCollection.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.parentTabs.setTabText(self.parentTabs.indexOf(self.playlistsTab), QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.b_Clear.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.b_Clear.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.svplyBttn.setToolTip(QtGui.QApplication.translate("MainWindow", "Save Playlist As", None, QtGui.QApplication.UnicodeUTF8))
        self.svplyBttn.setText(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.b_Shuffle.setToolTip(QtGui.QApplication.translate("MainWindow", "Turn Shuffle On", None, QtGui.QApplication.UnicodeUTF8))
        self.clearSearchPl.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear search field", None, QtGui.QApplication.UnicodeUTF8))
        self.clearSearchPl.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.srchPlist.setToolTip(QtGui.QApplication.translate("MainWindow", "Playlist Search", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistTree.setSortingEnabled(False)
        self.playlistTree.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistTree.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistTree.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistTree.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Genre", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setText(QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRescan_Collection.setText(QtGui.QApplication.translate("MainWindow", "Rescan Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Play Media", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimise_to_Tray.setText(QtGui.QApplication.translate("MainWindow", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimise_to_Tray.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Current.setText(QtGui.QApplication.translate("MainWindow", "Clear Current", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_Collection.setText(QtGui.QApplication.translate("MainWindow", "Update Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptTrack.setText(QtGui.QApplication.translate("MainWindow", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptAlbum.setText(QtGui.QApplication.translate("MainWindow", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRptPlaylist.setText(QtGui.QApplication.translate("MainWindow", "Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndOff.setText(QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndTrack.setText(QtGui.QApplication.translate("MainWindow", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRndAlbum.setText(QtGui.QApplication.translate("MainWindow", "Albums", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFavor.setText(QtGui.QApplication.translate("MainWindow", "Favor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Audio_CD.setText(QtGui.QApplication.translate("MainWindow", "Play Audio CD", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrevious_Track.setText(QtGui.QApplication.translate("MainWindow", "Previous Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Track.setText(QtGui.QApplication.translate("MainWindow", "Next Track", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRescan.setText(QtGui.QApplication.translate("MainWindow", "Rescan Collection", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
from PyQt4 import QtWebKit
import icons_rc
